import { Inter } from 'next/font/google'

import '@styles/collapsible.scss'
import '@styles/color-picker.scss'
import '@styles/global.scss'
import '@styles/scrollbar.scss'
import { ReactNode } from 'react'
import { Providers } from './providers'

// import localFont from "next/font/local";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="antialiased margin-0 min-h-screen flex flex-col bg-body text-base font-normal">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
